name:                 funcional-uno
version:              0.1.0.0
visibility:           public
id:                   funcional-uno-0.1.0.0-3GPLAJQF9JjFg8afYdq9Ht
key:                  funcional-uno-0.1.0.0-3GPLAJQF9JjFg8afYdq9Ht
license:              BSD-3-Clause
copyright:            2019 Author name here
maintainer:           example@example.com
author:               Author name here
homepage:             https://github.com/githubuser/funcional-uno#readme
description:
    Please see the README on GitHub at <https://github.com/githubuser/funcional-uno#readme>

abi:                  38d66bb6c59d4410892803e356fe3a9d
exposed:              True
exposed-modules:      Library Spec
import-dirs:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-uno/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/lib/x86_64-linux-ghc-9.6.6/funcional-uno-0.1.0.0-3GPLAJQF9JjFg8afYdq9Ht

library-dirs:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-uno/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/lib/x86_64-linux-ghc-9.6.6/funcional-uno-0.1.0.0-3GPLAJQF9JjFg8afYdq9Ht

library-dirs-static:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-uno/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/lib/x86_64-linux-ghc-9.6.6/funcional-uno-0.1.0.0-3GPLAJQF9JjFg8afYdq9Ht

dynamic-library-dirs:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-uno/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/lib/x86_64-linux-ghc-9.6.6

data-dir:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-uno/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/share/x86_64-linux-ghc-9.6.6/funcional-uno-0.1.0.0

hs-libraries:         HSfuncional-uno-0.1.0.0-3GPLAJQF9JjFg8afYdq9Ht
depends:
    base-4.18.2.1 hspec-2.11.10-FuFcmSfRp97EPrX4Y0mq7y
    pdeprelude-0.2.0.0-CPIA72aJW6mW5nFuYj7o0

haddock-interfaces:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-uno/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/doc/funcional-uno-0.1.0.0/funcional-uno.haddock

haddock-html:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-uno/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/doc/funcional-uno-0.1.0.0
