name:                 funcional-cuatro
version:              0.1.0.0
visibility:           public
id:                   funcional-cuatro-0.1.0.0-CQFluw2cECwJcg0RBfH3y0
key:                  funcional-cuatro-0.1.0.0-CQFluw2cECwJcg0RBfH3y0
license:              BSD-3-Clause
copyright:            2019 Author name here
maintainer:           example@example.com
author:               Author name here
homepage:             https://github.com/githubuser/funcional-cuatro#readme
description:
    Please see the README on GitHub at <https://github.com/githubuser/funcional-cuatro#readme>

abi:                  2a5a37373ea6fb5cfc036d228f25252a
exposed:              True
exposed-modules:      Library Spec
import-dirs:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-cuatro/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/lib/x86_64-linux-ghc-9.6.6/funcional-cuatro-0.1.0.0-CQFluw2cECwJcg0RBfH3y0

library-dirs:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-cuatro/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/lib/x86_64-linux-ghc-9.6.6/funcional-cuatro-0.1.0.0-CQFluw2cECwJcg0RBfH3y0

library-dirs-static:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-cuatro/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/lib/x86_64-linux-ghc-9.6.6/funcional-cuatro-0.1.0.0-CQFluw2cECwJcg0RBfH3y0

dynamic-library-dirs:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-cuatro/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/lib/x86_64-linux-ghc-9.6.6

data-dir:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-cuatro/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/share/x86_64-linux-ghc-9.6.6/funcional-cuatro-0.1.0.0

hs-libraries:         HSfuncional-cuatro-0.1.0.0-CQFluw2cECwJcg0RBfH3y0
depends:
    base-4.18.2.1 hspec-2.11.10-FuFcmSfRp97EPrX4Y0mq7y
    pdeprelude-0.2.0.0-CPIA72aJW6mW5nFuYj7o0

haddock-interfaces:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-cuatro/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/doc/funcional-cuatro-0.1.0.0/funcional-cuatro.haddock

haddock-html:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-cuatro/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/doc/funcional-cuatro-0.1.0.0
