name:                 funcional-tres
version:              0.1.0.0
visibility:           public
id:                   funcional-tres-0.1.0.0-Ftmp9jbShBUH25B6KAMuJp
key:                  funcional-tres-0.1.0.0-Ftmp9jbShBUH25B6KAMuJp
license:              BSD-3-Clause
copyright:            2019 Author name here
maintainer:           example@example.com
author:               Author name here
homepage:             https://github.com/githubuser/funcional-tres#readme
description:
    Please see the README on GitHub at <https://github.com/githubuser/funcional-tres#readme>

abi:                  c82b10f32407c7b4641cb7cd093c7b9f
exposed:              True
exposed-modules:      Library Spec
import-dirs:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-tres/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/lib/x86_64-linux-ghc-9.6.6/funcional-tres-0.1.0.0-Ftmp9jbShBUH25B6KAMuJp

library-dirs:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-tres/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/lib/x86_64-linux-ghc-9.6.6/funcional-tres-0.1.0.0-Ftmp9jbShBUH25B6KAMuJp

library-dirs-static:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-tres/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/lib/x86_64-linux-ghc-9.6.6/funcional-tres-0.1.0.0-Ftmp9jbShBUH25B6KAMuJp

dynamic-library-dirs:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-tres/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/lib/x86_64-linux-ghc-9.6.6

data-dir:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-tres/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/share/x86_64-linux-ghc-9.6.6/funcional-tres-0.1.0.0

hs-libraries:         HSfuncional-tres-0.1.0.0-Ftmp9jbShBUH25B6KAMuJp
depends:
    base-4.18.2.1 hspec-2.11.10-FuFcmSfRp97EPrX4Y0mq7y
    pdeprelude-0.2.0.0-CPIA72aJW6mW5nFuYj7o0

haddock-interfaces:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-tres/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/doc/funcional-tres-0.1.0.0/funcional-tres.haddock

haddock-html:
    /home/servasquezlizana/Documentos/Paradigmas/Funcional/funcional-tres/.stack-work/install/x86_64-linux/cb3b5e10edcf0bd9f880f94b7e31655b619a5fa8ed93967f57f982ba70057fd7/9.6.6/doc/funcional-tres-0.1.0.0
